services:
  - type: web_service
    name: srida-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    healthCheckPath: /api/health
    healthCheckTimeout: 100
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://srida:srida123@cluster0.mongodb.net/srida?retryWrites=true&w=majority"
      - key: JWT_SECRET
        value: "srida_jwt_F9GK2M4N8P3Q7R5S1T9V2W6X8Y4Z7"
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "10000"
      - key: FRONTEND_URL
        value: "https://srida-frontend.onrender.com"
    autoDeploy: true

  - type: static_site
    name: srida-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm ci && npm run build --if-present
    staticPublishPath: frontend/dist

# Notes: Replace ${MONGO_URI} and ${JWT_SECRET} with Render environment variables
# When you connect this repo to Render, set MONGO_URI to a MongoDB Atlas connection string
# or use a managed MongoDB service. The frontend static site assumes Angular builds into frontend/dist.
